# Generated by Django 4.1.3 on 2022-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('link', models.TextField(unique=True, verbose_name='Link on news origin')),
                ('raiting', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1)),
                ('is_posted', models.BooleanField(db_index=True, default=True, verbose_name='Posted?')),
                ('is_valued', models.BooleanField(default=True, verbose_name='Relation to sphere')),
            ],
        ),
    ]
